server:
  port: ${server_port}

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: ${database_url}
    password: ${database_password}
    username: ${database_username}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /swagger-ui.html

